sudo: required
services:
- docker
os:
- linux
language:
- generic
install:
- sudo apt-get install -y binfmt-support qemu-user-static
script:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- export REPO=alxchk/docker-old-tc
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- cd $TRAVIS_BUILD_DIR/$TC && ./download.sh >/dev/null
- cd $TRAVIS_BUILD_DIR/$TC && docker build -t alxchk/tc-$TC:$TAG .
- cd $TRAVIS_BUILD_DIR/$TC && docker push alxchk/tc-$TC:$TAG >/dev/null
cache:
  - $TRAVIS_BUILD_DIR/$TC/downloads
env:
  global:
  - secure: VS2LYBNubHFhmm1aN8mZ77PX8QS3bUv+1NVdl4AN6oKyleBKkhwQQM5cR0teXCT8UhKJ7SUsZk52ReHsjCgcNsYLzr79auuAGnvyBUtUY1dO/fbnNeF1cbimx/2Ry2iA7KzOblp1CHfnREcda8hDtxpBPYC8cqSaofPNxL/LAr3MmpavPqRVxy/4eHkIq178COZWpkeFyEM4bHT0wIeefNrEjOwRBsdr17gs8sLfOiWfJNwVF3UrVyaqDq8l08g7GfIv0IzUPGbh8xt/pMppNFcLMHg4EDy8k3DH9M+bAxW/Bdr2XToNGp46+j9kh8gN7LVKZxVRq6/Yx6rJjiWKFKeFiOoj1t1Wzmu8q8l97Gsj519kIl55n1R9rHbqGMgfZvdXetyLRt5tiAt0EDhMHSa2CtrDaPh0DirfCTvb/1nDwJ2kXEntk/TaxeLrBdYtBIuyG9nwBfPTEGy0heRGhZ9qAOk5UNpJaHbciGO9tKOuymc+jNHsfnjRgto9qsohikiPYcSPu6y0qZ2UFG3SbFWZ0KwkpMFKkU1gmuUD6Gil1UP5IVy0a+WrjTPQs0CFsLL3p1GYPFhC8hQOvssSwXb8ZEVWJTL5bwKpEU3Dxr+IKLPPQHkXYku93/XUklELG3HNLF9Mp5Mo8ADX6XhPQEUCSuAAYA8XVPQWXfJCoUQ=
  - secure: S+JOsgbrexIgCYpz0HNxGZoYxIhFRQFjJuQjMCJM8lSFpXmfe+8zfztp270FN9JUAeGEFE2kGF+GvdXmKWZGxlK4sCN86oaO3+yQoPazv9bN1Khle+SMVmFzG7OBgNnB/TR6OZa0mHVdyOmFH898dqEjcoK0kssAn08GraNDraaNa6Pv/SxH9wH6rIVbOK10xnHNzWziPMqjmCxa9NeubkT5+frpiOWJLnvf5q13/VqxhiELJ/HncpymSDcCutG/eRtnvs8XD+lNlrOXb/GL2fIxCiVSdDD3GGcs0ApdFJoqoio2druv7ODy+qP1JlgA0TJ0V8kAHHtsyjDR+pmoPyWcP+SSkN6muYM5I3Z9bkcce9NUEnsiLRA5m/t1Oy7iXPpqVi7qXkzE0NgJZABAScNOboRX0abNNIOdvnEIfAcIuIxNmtL5nRmN7gg6DXqlzax3YNpkgxHrMZxBkWPAyPQ7Z2L5tukN1QGMs3+b7tuXMb5dpta82CQe5q6vvUM9rAFiuPcd3QKW+55d2q5ga0EFq2PgGpYwMI3feMhhl1DG5kvdKOtxc53A2OGQVNpDeYD/Y73EgCaTeRyE4dsNDfth/NyPB1cvot3TO5u1vYIXOvH4sg7tPaCw8Y4M5EULm/dc19ZdiALrBd+AcnG7R7QEs6doq/9XM0QVpRW5Ars=
  matrix:
  - TC=linux32
  - TC=linux64
  - TC=windows
  - TC=android
